export const LOADING_BEGIN = "LOADING_BEGIN";
export const LOADING_FAILURE = "LOADING_FAILURE";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const SET_DESSERTS = "SET_DESSERTS";
export const REMOVE_DESSERT = "REMOVE_DESSERT";
export const ADD_DESSERT = "ADD_DESSERT";
